apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: rethinkdb-cluster
  labels:
    db: rethinkdb
spec:
  selector:
    matchLabels:
      db: rethinkdb
      role: replica
  replicas: 1
  serviceName: rethinkdb-driver
  template:
    metadata:
      labels:
        db: rethinkdb
        role: replica
    spec:
      terminationGracePeriodSeconds: 10
      serviceAccountName: rethinkdb-serviceaccount
      imagePullSecrets:
        - name: regcred
      containers:
        - image: docker.pkg.github.com/lucacasonato/rethinkdb-kubernetes/rethinkdb:latest
          name: rethinkdb
          env:
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          ports:
            - containerPort: 8080
              name: admin-port
            - containerPort: 28015
              name: driver-port
            - containerPort: 29015
              name: cluster-port
          volumeMounts:
            - mountPath: /data/rethinkdb_data
              name: rethinkdb-storage
  volumeClaimTemplates:
    - metadata:
        name: rethinkdb-storage
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 1Gi
