apiVersion: v1
kind: ServiceAccount
metadata:
  name: rethinkdb-serviceaccount
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: Role
metadata:
  name: rethinkdb-role
  namespace: default
rules:
  - apiGroups: [""]
    resources: ["endpoints"]
    verbs: ["get"]
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: RoleBinding
metadata:
  name: rethinkdb-rbac
  namespace: default
subjects:
  - kind: ServiceAccount
    name: rethinkdb-serviceaccount
roleRef:
  kind: Role
  name: rethinkdb-role
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
kind: Service
metadata:
  labels:
    db: rethinkdb
    role: replica
  name: rethinkdb-cluster
spec:
  ports:
    - port: 28015
      targetPort: 28015
  selector:
    db: rethinkdb
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: rethinkdb-nodes
  labels:
    db: rethinkdb
spec:
  selector:
    matchLabels:
      db: rethinkdb
  replicas: 3
  serviceName: rethinkdb-cluster
  template:
    metadata:
      labels:
        db: rethinkdb
    spec:
      terminationGracePeriodSeconds: 10
      serviceAccountName: rethinkdb-serviceaccount
      containers:
        - image: lucacasonato/rethinkdb-kubernetes:2.4.0
          name: rethinkdb
          env:
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          ports:
            - containerPort: 8080
              name: admin-port
            - containerPort: 28015
              name: driver-port
            - containerPort: 29015
              name: cluster-port
          volumeMounts:
            - mountPath: /data/rethinkdb_data
              name: rethinkdb-storage
  volumeClaimTemplates:
    - metadata:
        name: rethinkdb-storage
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 1Gi
