apiVersion: v1
kind: ServiceAccount
metadata:
  name: rethinkdb-serviceaccount
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: Role
metadata:
  name: rethinkdb-role
  namespace: default
rules:
  - apiGroups: [""]
    resources: ["endpoints"]
    verbs: ["get"]
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: RoleBinding
metadata:
  name: rethinkdb-rbac
  namespace: default
subjects:
  - kind: ServiceAccount
    name: rethinkdb-serviceaccount
roleRef:
  kind: Role
  name: rethinkdb-role
  apiGroup: rbac.authorization.k8s.io
